### ISSUE TITLE
[1pt] Final group capstone: set up Kanban board

### ISSUE THREAD

**Issue by shahadat3669** [shahadat3669/rent-home-now-api#21]
In this project, I am working with 2 other partners. Here is @shahadat3669, @sambeck87, @GutemaG. We prepare a Kanban board with a [GitHub project](https://github.com/users/shahadat3669/projects/9).

Others Requirements:

- Create cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). Each task  is a separate card that:
  - Has a descriptive title.
  - Has the number of points in the [Xpt] prefix.
  - Has a description of the task.
- Each of the team members should assign themselves to the cards 

**Screenshot of our kanban board:**
![Rent-Home-Now](https://user-images.githubusercontent.com/55840999/236042261-3f31ae1b-e926-482f-b679-621648fe009a.png)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Meltrust** [comment]
Hi @GutemaG,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All tasks have been pointed, assigned, and have descriptions ✔️
- Pointings meet the equality rule ✔️  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
